services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: mc-fabric-server
    ports:
      - "25565:25565"
    env_file:
      - config/mc_server_version.env
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
    volumes:
      - ./data:/data
      - ./mods:/data/mods
      - ./config:/data/config
    restart: unless-stopped
